# Funding options for this project
# Uncomment and add your funding platform usernames as needed

github: [okdaichi]
# patreon: username
# ko_fi: username
# buy_me_a_coffee: username
# custom: ['https://example.com']
