# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: qumo

before:
  hooks:
    - go mod tidy

builds:
  - id: qumo
    main: .
    binary: qumo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/okdaichi/qumo/internal/version.version={{.Version}}
      - -X github.com/okdaichi/qumo/internal/version.commit={{.ShortCommit}}
      - -X github.com/okdaichi/qumo/internal/version.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - config.relay.yaml
      - config.sdn.yaml

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: okdaichi
    name: qumo
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"
